### ISSUE TITLE
крафт  котла 1 другого дороже

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#10]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/b33d9c89-d595-469f-aa59-47856e6ce4a1)
 
 
 id recipe :  Recipe ID: tfc:crafting/vanilla/cauldron
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/f8645732-bd02-4237-9a6d-f500de0102f8)

id recipe :  Recipe ID: minecraft:cauldron
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/45430e8f-8091-4080-8f0b-bf341800d080)

**Comment by Damodigy** [comment]
Fixed убран последний рецепт ( ванильный )
