### ISSUE TITLE
изменить крафт андезит сплава 

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#11]
в крафте юзается только ванильный андесит
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/472810db-7405-4526-a855-f4af32e625d9)

![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/31b0fdc1-5863-4c8d-920e-1b516f8498b3)

**Comment by Damodigy** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/43088109/ee459922-88ac-409c-828b-5980799300e1)
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/43088109/720256fa-b402-4cc0-b6b4-16845f3d6e9e)

**Comment by Damodigy** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/43088109/c6128f82-1b72-40f9-acaf-71166dea110b)
