### ISSUE TITLE
убрать крафт ванильного crossbow и tripwire_hook

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#12]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/cc8e4342-5e0c-4af1-b849-f5094c4ee3ee)
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/262c8649-0a3b-455e-ba02-d614be61421e)

надо убрать лишние крафты

**Comment by Damodigy** [comment]
Fixed
