### ISSUE TITLE
гоу шобы компасы ломались когда рядом с ними руды железа 

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#18]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/fcda4258-ab34-4774-8a77-3d85b6f7c4f8)

**Comment by Damodigy** [comment]
Ну ты и черт)

**Comment by FriendlyCube** [comment]
а че оно закрыто
