### ISSUE TITLE
а мона пазалуфта шобы ...

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#23]
хочу шобы пока я нахожусь в инвенторе 
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/f2fcbce5-dcc0-4878-a48b-bcda28dcbcc1)
задний фон не мутился

**Comment by SpeeeDCraft** [comment]
Такого не будет
