### ISSUE TITLE
Нет

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#26]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/c4e9a85a-2689-4e61-a838-3fd71157ef21)

**Comment by FriendlyCube** [comment]
я читерить не буду
но надо это починить а то зная этого чела на даме я думаю что он захочет эт осделать

**Comment by FriendlyCube** [comment]
ща починю наверно

**Comment by FriendlyCube** [comment]
изменил крафт с 4 на 1 , но надо менять не крафт а стоимость сопортв с 200 на 25

**Comment by FriendlyCube** [comment]
а вообще это нахой разрабам росии писать

**Comment by FriendlyCube** [comment]
розии*

**Comment by FriendlyCube** [comment]
уважаемый, что значит нет

**Comment by Xikaro** [comment]
![Screenshot_157](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/55663835/3012d446-bf0c-4a5c-8430-71871a6ed42a)

**Comment by FriendlyCube** [comment]
понял,спасибо

**Comment by FriendlyCube** [comment]
а что насчет того чтобы написать разрабам розии

**Comment by Xikaro** [comment]
пока не приоритет и его бы обновить

**Comment by FriendlyCube** [comment]
а что насчет моего реквеста
