### ISSUE TITLE
Придумать как получить пчёл

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#34]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/128903188/df21510d-abca-4bff-87c7-5519b66a49ca)
Предлагаю добавить Productive Bees, там есть призывалки для пчёл, и отредачить крафты

**Comment by FriendlyCube** [comment]
предлагаю добавить сумон возле фруктовых деревьев

**Comment by Yorodoshi** [comment]
Их возможн![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/128903188/e8f50cfa-06b3-4f29-88e2-3322d8c9a93a) получать, просто постройте вокруг пасеки цветы !!!
