### ISSUE TITLE
текстура песка во время снегопада

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#4]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/2107fcc0-e9fe-4d6f-bd7e-4166cd303f91)
 предлогаю убрать

**Comment by Xikaro** [comment]
Что? Кого убрать? Какую текстуру?

**Comment by FriendlyCube** [comment]
кароч когда ходишь по песку на экране появляется песок
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/fd78bba8-3230-4530-9ab5-b0300de0a55e)
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/1f6448d4-7cb4-4f48-a527-d72bfccac2b7)
даже если песок находится под снегом, я предлагаю убрать появление текстуры когда над песком есть блоки снега

**Comment by Xikaro** [comment]
Пусть будет
