### ISSUE TITLE
блок глины можно обработать в тропинку

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFM-Modpack-1.18.x#7]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/a830e145-2783-40a9-947f-203a8182200c)
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/112543401/6a1f0ef9-5f8f-4398-9d13-cb3f6025f991)

**Comment by SpeeeDCraft** [comment]
тру механика

**Comment by FriendlyCube** [comment]
это надо писать челам тфк?

**Comment by Xikaro** [comment]
Нет, это хорошая механика, я бы еще сделал выпадение глины к примеру

**Comment by Damodigy** [comment]
Готово :D

**Comment by Damodigy** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFM-Modpack-1.18.x/assets/43088109/1f4a04b2-b3c0-40c2-a18d-885d199045cb)
